name: Deploy Static Files "sanjose-com" # Nombre del workflow.

on:
  push:
    branches:
      - sanjose-com # Ejecutar el workflow solo cuando haya un push a la rama `sanjose-com`.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Obtiene el código del repositorio.

      - name: Set up .env file
        run: |
          echo "SITE=https://cursoagenteinmobiliarioperu.com" >> .env
          echo "API_INFORMATION=https://cursoagenteinmobiliarioperu.com/consultas/seguimiento.php" >> .env
          echo "PUBLIC_RECAPTCHA_SITE_KEY=6LchufsnAAAAAKgEzDQWSH1nLyG_1ttI-7tDNvl8" >> .env

      - name: Install dependencies
        run: |
          npm install
          npm run build # Genera los archivos estáticos en el directorio `dist`.

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.0 # Usa un paquete para subir archivos al servidor vía SCP.
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME_SANJOSE_COM }}
          key: ${{ secrets.PRIVATE_KEY_SANJOSE_COM }}
          port: ${{ secrets.PORT }} # Cambia el puerto si tu servidor usa uno diferente.
          source: 'dist/*' # Selecciona SOLO el contenido de `dist`.
          target: '/tmp/dist_upload' # Subimos a una carpeta temporal en el servidor.

      - name: Configure server
        uses: appleboy/ssh-action@v1.0.0 # Conexión SSH para ejecutar comandos en el servidor.
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME_SANJOSE_COM }}
          key: ${{ secrets.PRIVATE_KEY_SANJOSE_COM }}
          port: ${{ secrets.PORT }}
          script: |
            # Limpia el directorio de destino en el servidor.
            rm -rf ${{ secrets.WORKING_DIRECTORY_SANJOSE_COM }}/*

            # Mueve el contenido de la carpeta temporal al directorio de destino.
            mv /tmp/dist_upload/* ${{ secrets.WORKING_DIRECTORY_SANJOSE_COM }}

            # Configura permisos adecuados.
            chmod -R 755 ${{ secrets.WORKING_DIRECTORY_SANJOSE_COM }}

            # Elimina la carpeta temporal.
            rm -rf /tmp/dist_upload
